#!/bin/bash

# Remove previous versions of 'cyberops' image
docker images --format '{{.Repository}}:{{.Tag}} {{.ID}}' | grep "^cyberops:" | awk '{print $2}' | xargs -r docker rmi

# Build the new image
docker build -t cyberops .
