#!/bin/bash

# Remove previous versions of 'cyberops' image
docker images --format '{{.Repository}}:{{.Tag}} {{.ID}}' | grep "^cyberops:" | awk '{print $2}' | xargs -r docker rmi

CACHE_ARG=""
DEBUG=""
while getopts "cd" opt; do
   case $opt in
      c)
         CACHE_ARG="--no-cache"
      ;;
      d)
         DEBUG="--debug"
      ;;
      *)
         ;;
   esac
done
shift $((OPTIND -1))

# Build the new image
docker $DEBUG build $CACHE_ARG -t cyberops .

